# -*- coding: utf-8 -*-
"""dog_breed_backend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nPuuJX6MJeH-ZT3PXq8GmIjTQW_pGiPy
"""

# @title 1. Install Dependencies
!pip install fastapi uvicorn pyngrok python-dotenv psycopg2-binary tensorflow pillow python-multipart ultralytics numpy

!gdown --id 1ArGMnfkvHSxNH0UUY57u-vDy46G3KQxF
!unzip new_Backend.zip -d /content

# @title 2. Set Working Directory
import os

# This assumes you uploaded the folder named 'Backend'
project_folder = "/content/Backend"

if os.path.exists(project_folder):
    os.chdir(project_folder)
    print(f"Working directory set to: {os.getcwd()}")
else:
    print(f"Error: Folder '{project_folder}' not found. Please upload your Backend folder to the Files section.")

# @title 3. Configuration (Supabase & Ngrok)
import os

# @markdown ### Supabase Credentials
SUPABASE_URL = "https://jxnvdmuoiqvmbaoyprxc.supabase.co" # @param {type:"string"}
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4bnZkbXVvaXF2bWJhb3lwcnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5NTgyNjAsImV4cCI6MjA3OTUzNDI2MH0.SKon-Sd1ceTLQLnvqxfzSOqCVGW_4MWwD__4XGb796c" # @param {type:"string"}

# @markdown ### Ngrok Setup
# Get your token from https://dashboard.ngrok.com/get-started/your-authtoken
ngrok_auth_token = "2uyF5w6LfmR1x5CPz53j5GUmaPS_5Xqokx5UqjpqofDEmUnAM" # @param {type:"string"}

# Create .env file
env_content = f"""
SUPABASE_URL={SUPABASE_URL}
SUPABASE_KEY={SUPABASE_KEY}
"""

with open(".env", "w") as f:
    f.write(env_content)

print(".env file created successfully.")

# Authenticate Ngrok
if ngrok_auth_token:
    !ngrok config add-authtoken {ngrok_auth_token}
    print("Ngrok authenticated.")
else:
    print("Warning: No Ngrok auth token provided. The tunnel might fail.")

!pip install supabase

# @title 4. Run Server
import threading
import time
from pyngrok import ngrok
import uvicorn
from app.main import app


# Start Ngrok Tunnel on port 8000
port = 8000
public_url = ngrok.connect(port).public_url
print(f"\n\u001b[92m\u2714 Public URL: {public_url}\u001b[0m\n")

# Function to run Uvicorn server
def run_uvicorn():
    config = uvicorn.Config(app, host="0.0.0.0", port=port)
    server = uvicorn.Server(config)
    server.run()

# Run Uvicorn server in a separate thread
thread = threading.Thread(target=run_uvicorn)
thread.start()

print("Uvicorn server started in a background thread.")
print("You can now access your FastAPI application via the public URL.")
# The main thread can now proceed or simply finish, and the uvicorn server will keep running in the background.

